### ISSUE TITLE
Sorting by a property from translation table in the event_selection is not possible

### ISSUE THREAD

**Issue by manuxi** [sulu/sulu-workshop#33]
| Q | A
| --- | ---
| Bug? | yes
| Sulu Version | 2.2.3
| Browser Version | Chrome Version 89.0.4389.90 

#### Actual Behavior

Sort by 'Title' in the event_selection is not possible. The generated query is executed on the event table, there is no join to the translation table.
Error:
[Semantical Error] line 0, col 27 near 'event_translation.title': Error: 'event_translation' is not defined.
Doctrine\\ORM\\Query\\QueryException: SELECT DISTINCT entity.id, event_translation.title FROM App\\Entity\\Event entity ORDER BY event_translation.title asc

If I use a property of the event table (e.g. startDate), everything works fine.

#### Expected Behavior

Sorting by a translated property works.

#### Steps to Reproduce

Click on the filter symbol, select 'Title' in the sort by dropdown.

**Comment by nnatter** [comment]
I dont think there is a way to sort the `event_selection` automatically, it can only be sorted manually in the administration interface. 

Is it possible that you are talking about the `events` data-provider for the `smart_content`? 
Which step of the workshop implements the functionality?

**Comment by manuxi** [comment]
Yes I was talking about the EventDataProvider (self::createConfigurationBuilder()->->enableSorting([['column' => 'event_translation.title', ...). If you choose this in the event_selection the above Exception is thrown.

**Comment by nnatter** [comment]
You are right, this looks like a typo indeed. The `EventDataProvider` should use `translation` instead of `event_translation` to match the alias that is used in the `EventRepository::appendJoins` method:
https://github.com/sulu/sulu-workshop/blob/5f91239f24e24006bddaf848078bd611ca868018/src/Repository/EventRepository.php#L89

I have updated the code. Thanks for reporting!

**Comment by manuxi** [comment]
Sorry, but it still didn't work. Since I'd like to understand how filtering in the translation table works, I debugged a bit.
The main query is correctly prepared in DataProviderRepositoryTrait::findByFilters(). To query the correct ids, the method DataProviderRepositoryTrait::findByFiltersIds() is called then. There the $filters['sortBy'] is still alive and responsible an incorrect query to get the ids ("SELECT DISTINCT entity.id, translation.title FROM App\\Entity\\Event entity ORDER BY translation.title asc"). If the sortBy isn't considered (I put in a "false && isset($filters['sortBy'])" in line 106), the filter works as expected. However, I don't know which side effects it could cause when the $filters['sortBy'] is omitted in DataProviderRepositoryTrait::findByFiltersIds()...

**Comment by nnatter** [comment]
> Sorry, but it still didn't work.

Please include the steps to reproduce the problem if something does not work for you. I could not reproduce any problems in this repository. 

I figured eventually that the code of this repository causes issues with newer Sulu versions (which are not used in this repository at the moment), but that took me quite some time. I have updated the code of the `EventRepository` to be compatible with newer versions of Sulu.

> If the sortBy isn't considered (I put in a "false && isset($filters['sortBy'])" in line 106), the filter works as expected. However, I don't know which side effects it could cause when the $filters['sortBy'] is omitted in DataProviderRepositoryTrait::findByFiltersIds()

This will break things if you are using the sorting together with pagination. The pagination will not respect the given sorting and the items will only be sorted within the current page. In general, the `findByFiltersIds` method is responsible for querying the ids that should be included in the result. The `findByFilters` uses this ids to query the actual data.

**Comment by manuxi** [comment]
> Please include the steps to reproduce the problem if something does not work for you. I could not reproduce any problems in this repository.

Sorry if was not clear. I don't want to waste your time. Anyways, I made a checkout of the workshop just to check the code here some weeks ago. Sulu Version is 2.2.3. I removed the security-checker.
Changing the 'Sort by' to 'title' (which is the one from the translation table) in 'Configuring events':
![config-events](https://user-images.githubusercontent.com/11303615/113134950-c87ad000-9221-11eb-89f3-28b42f425f6e.png)
is causing this exception:
![exception02](https://user-images.githubusercontent.com/11303615/113135036-e5170800-9221-11eb-8235-e85dd7307936.png)
I checked that since the "Sort by" didn't work on my custom entity with translation table didn't work either.
I just made a git pull to geht your changes (and yes, cleared the cache :)). On my platform the problem still exists. I'll dig deeper when I have some spare time.

**Comment by nnatter** [comment]
I am not sure sure if a `git pull` is enough in your case, we do amend commits in this repository to make sure that there is a single commit per assignment 🙂 

I would recommend to clone the project again to make sure that you are using the latest code. After cloning the project, you can checkout the `assignment/11` and test the the functionality on the `Events` page.

**Comment by manuxi** [comment]
Oh my... haven't thought about git pull. With your changes in the Repository class I can confirm its woking now. Thank you very much!

**Comment by nnatter** [comment]
Thats good to hear! You are welcome 🙂
